default_platform(:ios)

platform :ios do
  desc "Build App Store IPA (Clean & Stable)"
  lane :build_appstore do |options|

    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: ENV["ASC_KEY_PATH"],
      in_house: false
    )

    match(
      type: "appstore",
      app_identifier: options[:bundle_id],
      team_id: ENV["IOS_TEAM_ID"],
      api_key: api_key,
      readonly: false
    )

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      output_directory: "../build/ios/ipa",
      output_name: "app.ipa",
      clean: true
    )
  end
end
